language: go
go:
  - "1.10"

branches:
  only:
    - master

# this downloads and unpacks netlifyctl
before_install:
  - wget https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz
  - tar -xvf netlifyctl-linux-amd64-0.4.0.tar.gz

install:
  - ./s/travis_install.sh

script:
  - ./s/travis_build.sh
