name = "blog"
type = "webpack"
account_id = "71694ef61795ecbe1bc331d217dbd7a7"
workers_dev = true

route = "blog.kowalczyk.info/*"
zone_id = "80741a2b8f1a5726bf84ac76d73ff8f9"

[site]
bucket = "./netlify_static"
entry-point = "workers-site"
