name = "blog"
type = "webpack"
workers_dev = true

routes = ["blog.kowalczyk.info/*", "kowalczyk.info/*"]
zone_id = "80741a2b8f1a5726bf84ac76d73ff8f9"

[site]
bucket = "./netlify_static"
entry-point = "workers-site"
